### ISSUE TITLE
taxtable: ValueError: 'section' is not in list

### ISSUE THREAD

**Issue by openpaul** [fhcrc/taxtastic#128]
I ran:
```
taxit new_database taxonomy.db
```
Followed by
```
taxit taxtable taxonomy.db -t 5599 
```
And get the error:
```
Traceback (most recent call last):
  File "taxtastic-env/bin/taxit", line 11, in <module>
    load_entry_point('taxtastic==0.8.9', 'console_scripts', 'taxit')()
  File "taxtastic-env/lib/python3.6/site-packages/taxtastic/scripts/taxit.py", line 51, in main
    return action(arguments)
  File "taxtastic-env/lib/python3.6/site-packages/taxtastic/subcommands/taxtable.py", line 150, in action
    sorted_ranks = sorted(all_ranks, key=order_ranks(tax.ranks[::-1]))
  File "taxtastic-env/lib/python3.6/site-packages/taxtastic/subcommands/taxtable.py", line 77, in _inner
    return (ref_ranks.index(rank), 0)
ValueError: 'section' is not in list

```
Other taxids work fine. I am unsure what seems to be the issue here.

I am using 
```
taxit --version
taxit v0.8.9
```

**Comment by crosenth** [comment]
Thank you Paul for raising Issue.  I am able to reproduce this and am working on a fix.

**Comment by crosenth** [comment]
Go ahead and update taxtastic to version v0.8.11 either with pip (from PyPi) or from Github (https://github.com/fhcrc/taxtastic/releases/tag/v0.8.11).  

Thanks again for raising this Issue.  Let me know if anything else comes up.

**Comment by openpaul** [comment]
This seems to have fixed it.  Thank you.
