### ISSUE TITLE
ValueError: u'clade' is not in list

### ISSUE THREAD

**Issue by santcamille** [fhcrc/taxtastic#136]
Hello, I'm trying to use taxtable. I first ran: 
`taxit new_database taxonomy.db`
Then I tried to use taxtable:
`taxit taxtable taxonomy.db -f tax_ids.txt -o taxa.csv`
but I get the error:
```
Traceback (most recent call last):
  File "/home/pc/taxtastic/taxtastic_env_bis/bin/taxit", line 8, in <module>
    sys.exit(main())
  File "/home/pc/taxtastic/taxtastic_env_bis/local/lib/python2.7/site-packages/taxtastic/scripts/taxit.py", line 51, in main
    return action(arguments)
  File "/home/pc/taxtastic/taxtastic_env_bis/local/lib/python2.7/site-packages/taxtastic/subcommands/taxtable.py", line 150, in action
    sorted_ranks = sorted(all_ranks, key=order_ranks(tax.ranks[::-1]))
  File "/home/pc/taxtastic/taxtastic_env_bis/local/lib/python2.7/site-packages/taxtastic/subcommands/taxtable.py", line 77, in _inner
    return (ref_ranks.index(rank), 0)
ValueError: u'clade' is not in list
```
I also tried:
`taxit taxtable taxonomy.db -t 1280`
And I get the same error message.

I'm using taxtastic v0.8.11

I'm not sure what is going on but I checked and the NCBI taxonomy database had just been updated, maybe that's why...
Thanks

**Comment by crosenth** [comment]
Hi santcamille, I believe this is related to Issue https://github.com/fhcrc/taxtastic/issues/133 which we will have a fix for shortly.  Thank you for raising this Issue

**Comment by crosenth** [comment]
Please see version v0.9.0 - https://github.com/fhcrc/taxtastic/releases/tag/v0.9.0
