### ISSUE TITLE
MetaData.reflect() missing 1 required positional argument: 'bind'

### ISSUE THREAD

**Issue by lpipes** [fhcrc/taxtastic#151]
I can't seem to generate the `0_taxonomyfromtaxids.csv` file from this command (I attached my two files `0.csv` and `0_taxid.txt`):
```
taxit taxtable ncbi_taxonomy.db -f 0_taxid.txt -i 0.csv -o 0_taxonomyfromtaxids.csv
Traceback (most recent call last):
  File "/space/s1/lenore/software/taxtastic/taxit.py", line 22, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "/space/s1/lenore/software/taxtastic/taxtastic/scripts/taxit.py", line 51, in main
    return action(arguments)
           ^^^^^^^^^^^^^^^^^
  File "/space/s1/lenore/software/taxtastic/taxtastic/subcommands/taxtable.py", line 130, in action
    tax = Taxonomy(engine, schema=args.schema)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/space/s1/lenore/software/taxtastic/taxtastic/taxonomy.py", line 72, in __init__
    self.meta.reflect()
TypeError: MetaData.reflect() missing 1 required positional argument: 'bind'
```
[0.csv](https://github.com/fhcrc/taxtastic/files/11143528/0.csv)
[0_taxid.txt](https://github.com/fhcrc/taxtastic/files/11143529/0_taxid.txt)

**Comment by nhoffman** [comment]
This should be fixed in v0.10.0 - please reopen or submit a new issue if you still see the error.
