### ISSUE TITLE
TypeError: MetaData.reflect() missing 1 required positional argument: 'bind'

### ISSUE THREAD

**Issue by lpipes** [fhcrc/taxtastic#154]
Hello, I can't get this to work with any taxid

```
 taxit taxtable ncbi_taxonomy.db -t 1
Traceback (most recent call last):
  File "/home/lenore/.local/bin/taxit", line 33, in <module>
    sys.exit(load_entry_point('taxtastic==0.8.10+dirty', 'console_scripts', 'taxit')())
  File "/home/lenore/.local/lib/python3.10/site-packages/taxtastic-0.8.10+dirty-py3.10.egg/taxtastic/scripts/taxit.py", line 51, in main
    return action(arguments)
  File "/home/lenore/.local/lib/python3.10/site-packages/taxtastic-0.8.10+dirty-py3.10.egg/taxtastic/subcommands/taxtable.py", line 133, in action
    tax = Taxonomy(engine, schema=args.schema)
  File "/home/lenore/.local/lib/python3.10/site-packages/taxtastic-0.8.10+dirty-py3.10.egg/taxtastic/taxonomy.py", line 72, in __init__
    self.meta.reflect()
TypeError: MetaData.reflect() missing 1 required positional argument: 'bind'
```

**Comment by nhoffman** [comment]
This should be fixed in v0.10.0 - please reopen or submit a new issue if you still see the error.
