### ISSUE TITLE
running taxit error. pkg_resources.DistributionNotFound: xlrd

### ISSUE THREAD

**Issue by blancaverag** [fhcrc/taxtastic#88]
When running taxit I am encountering the following error. 
`taxit`
Traceback (most recent call last):
  File "/usr/local/bin/taxit", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2805, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 696, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 594, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: xlrd

The output of the locate command shows it is in more than one place:
/usr/local/bin/anaconda/lib/python2.7/site-packages/xlrd; 
/usr/local/bin/anaconda/pkgs/xlrd-0.9.3-py27_0; 
/usr/share/doc/python-xlrd-0.6.1

Any idea of how to solve this?
Thank you!

**Comment by crosenth** [comment]
Hi blancaverag,

Sorry to be just getting around to this.  Are you still having issues running taxit?

Chris

**Comment by blancaverag** [comment]
Hi Chris,

Yes, I do. Any ideas?

Thank you!

2017-04-20 23:24 GMT+02:00 Chris Rosenthal <notifications@github.com>:

**Comment by nhoffman** [comment]
I'm guessing you've moved on from this, but Please repoen if there are problems with the latest version.
